# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robotarminterface/moveServos.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import robotarminterface.msg

class moveServos(genpy.Message):
  _md5sum = "4a71efd697b71e458b626f0c557f215a"
  _type = "robotarminterface/moveServos"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """servoPosition[] servos
uint32 time

================================================================================
MSG: robotarminterface/servoPosition
uint32 servoId
int32 position"""
  __slots__ = ['servos','time']
  _slot_types = ['robotarminterface/servoPosition[]','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       servos,time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(moveServos, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.servos is None:
        self.servos = []
      if self.time is None:
        self.time = 0
    else:
      self.servos = []
      self.time = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.servos)
      buff.write(_struct_I.pack(length))
      for val1 in self.servos:
        _x = val1
        buff.write(_get_struct_Ii().pack(_x.servoId, _x.position))
      buff.write(_get_struct_I().pack(self.time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.servos is None:
        self.servos = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.servos = []
      for i in range(0, length):
        val1 = robotarminterface.msg.servoPosition()
        _x = val1
        start = end
        end += 8
        (_x.servoId, _x.position,) = _get_struct_Ii().unpack(str[start:end])
        self.servos.append(val1)
      start = end
      end += 4
      (self.time,) = _get_struct_I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.servos)
      buff.write(_struct_I.pack(length))
      for val1 in self.servos:
        _x = val1
        buff.write(_get_struct_Ii().pack(_x.servoId, _x.position))
      buff.write(_get_struct_I().pack(self.time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.servos is None:
        self.servos = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.servos = []
      for i in range(0, length):
        val1 = robotarminterface.msg.servoPosition()
        _x = val1
        start = end
        end += 8
        (_x.servoId, _x.position,) = _get_struct_Ii().unpack(str[start:end])
        self.servos.append(val1)
      start = end
      end += 4
      (self.time,) = _get_struct_I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Ii = None
def _get_struct_Ii():
    global _struct_Ii
    if _struct_Ii is None:
        _struct_Ii = struct.Struct("<Ii")
    return _struct_Ii
