// Generated by gencpp from file robotarminterface/armInstruction.msg
// DO NOT EDIT!


#ifndef ROBOTARMINTERFACE_MESSAGE_ARMINSTRUCTION_H
#define ROBOTARMINTERFACE_MESSAGE_ARMINSTRUCTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotarminterface
{
template <class ContainerAllocator>
struct armInstruction_
{
  typedef armInstruction_<ContainerAllocator> Type;

  armInstruction_()
    : instruction()
    , time(0)  {
    }
  armInstruction_(const ContainerAllocator& _alloc)
    : instruction(_alloc)
    , time(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _instruction_type;
  _instruction_type instruction;

   typedef uint32_t _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::robotarminterface::armInstruction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotarminterface::armInstruction_<ContainerAllocator> const> ConstPtr;

}; // struct armInstruction_

typedef ::robotarminterface::armInstruction_<std::allocator<void> > armInstruction;

typedef boost::shared_ptr< ::robotarminterface::armInstruction > armInstructionPtr;
typedef boost::shared_ptr< ::robotarminterface::armInstruction const> armInstructionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotarminterface::armInstruction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotarminterface::armInstruction_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotarminterface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'robotarminterface': ['/home/owner/git/Kinematica/src/catkin_ws/src/kinematics/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotarminterface::armInstruction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotarminterface::armInstruction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotarminterface::armInstruction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotarminterface::armInstruction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotarminterface::armInstruction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotarminterface::armInstruction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotarminterface::armInstruction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dde04e15fd9ee87f96fc4cbc41f78428";
  }

  static const char* value(const ::robotarminterface::armInstruction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdde04e15fd9ee87fULL;
  static const uint64_t static_value2 = 0x96fc4cbc41f78428ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotarminterface::armInstruction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotarminterface/armInstruction";
  }

  static const char* value(const ::robotarminterface::armInstruction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotarminterface::armInstruction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string instruction\n\
uint32 time\n\
";
  }

  static const char* value(const ::robotarminterface::armInstruction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotarminterface::armInstruction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.instruction);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct armInstruction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotarminterface::armInstruction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotarminterface::armInstruction_<ContainerAllocator>& v)
  {
    s << indent << "instruction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.instruction);
    s << indent << "time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTARMINTERFACE_MESSAGE_ARMINSTRUCTION_H
