// Generated by gencpp from file robotarminterface/moveServos.msg
// DO NOT EDIT!


#ifndef ROBOTARMINTERFACE_MESSAGE_MOVESERVOS_H
#define ROBOTARMINTERFACE_MESSAGE_MOVESERVOS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robotarminterface/servoPosition.h>

namespace robotarminterface
{
template <class ContainerAllocator>
struct moveServos_
{
  typedef moveServos_<ContainerAllocator> Type;

  moveServos_()
    : servos()
    , time(0)  {
    }
  moveServos_(const ContainerAllocator& _alloc)
    : servos(_alloc)
    , time(0)  {
  (void)_alloc;
    }



   typedef std::vector< ::robotarminterface::servoPosition_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::robotarminterface::servoPosition_<ContainerAllocator> >::other >  _servos_type;
  _servos_type servos;

   typedef uint32_t _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::robotarminterface::moveServos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotarminterface::moveServos_<ContainerAllocator> const> ConstPtr;

}; // struct moveServos_

typedef ::robotarminterface::moveServos_<std::allocator<void> > moveServos;

typedef boost::shared_ptr< ::robotarminterface::moveServos > moveServosPtr;
typedef boost::shared_ptr< ::robotarminterface::moveServos const> moveServosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotarminterface::moveServos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotarminterface::moveServos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotarminterface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'robotarminterface': ['/home/owner/git/Kinematica/src/catkin_ws/src/kinematics/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotarminterface::moveServos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotarminterface::moveServos_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotarminterface::moveServos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotarminterface::moveServos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotarminterface::moveServos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotarminterface::moveServos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotarminterface::moveServos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a71efd697b71e458b626f0c557f215a";
  }

  static const char* value(const ::robotarminterface::moveServos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a71efd697b71e45ULL;
  static const uint64_t static_value2 = 0x8b626f0c557f215aULL;
};

template<class ContainerAllocator>
struct DataType< ::robotarminterface::moveServos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotarminterface/moveServos";
  }

  static const char* value(const ::robotarminterface::moveServos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotarminterface::moveServos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servoPosition[] servos\n\
uint32 time\n\
\n\
================================================================================\n\
MSG: robotarminterface/servoPosition\n\
uint32 servoId\n\
int32 position\n\
";
  }

  static const char* value(const ::robotarminterface::moveServos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotarminterface::moveServos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.servos);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct moveServos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotarminterface::moveServos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotarminterface::moveServos_<ContainerAllocator>& v)
  {
    s << indent << "servos[]" << std::endl;
    for (size_t i = 0; i < v.servos.size(); ++i)
    {
      s << indent << "  servos[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::robotarminterface::servoPosition_<ContainerAllocator> >::stream(s, indent + "    ", v.servos[i]);
    }
    s << indent << "time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTARMINTERFACE_MESSAGE_MOVESERVOS_H
