// Generated by gencpp from file robotarminterface/singleServo.msg
// DO NOT EDIT!


#ifndef ROBOTARMINTERFACE_MESSAGE_SINGLESERVO_H
#define ROBOTARMINTERFACE_MESSAGE_SINGLESERVO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotarminterface
{
template <class ContainerAllocator>
struct singleServo_
{
  typedef singleServo_<ContainerAllocator> Type;

  singleServo_()
    : servoId(0)
    , position(0)
    , time(0)  {
    }
  singleServo_(const ContainerAllocator& _alloc)
    : servoId(0)
    , position(0)
    , time(0)  {
  (void)_alloc;
    }



   typedef uint32_t _servoId_type;
  _servoId_type servoId;

   typedef uint32_t _position_type;
  _position_type position;

   typedef uint32_t _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::robotarminterface::singleServo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotarminterface::singleServo_<ContainerAllocator> const> ConstPtr;

}; // struct singleServo_

typedef ::robotarminterface::singleServo_<std::allocator<void> > singleServo;

typedef boost::shared_ptr< ::robotarminterface::singleServo > singleServoPtr;
typedef boost::shared_ptr< ::robotarminterface::singleServo const> singleServoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotarminterface::singleServo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotarminterface::singleServo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotarminterface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'robotarminterface': ['/home/owner/git/Kinematica/src/catkin_ws/src/kinematics/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotarminterface::singleServo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotarminterface::singleServo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotarminterface::singleServo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotarminterface::singleServo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotarminterface::singleServo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotarminterface::singleServo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotarminterface::singleServo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39faf3391f2b3261e444ffb062992407";
  }

  static const char* value(const ::robotarminterface::singleServo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39faf3391f2b3261ULL;
  static const uint64_t static_value2 = 0xe444ffb062992407ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotarminterface::singleServo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotarminterface/singleServo";
  }

  static const char* value(const ::robotarminterface::singleServo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotarminterface::singleServo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 servoId\n\
uint32 position\n\
uint32 time\n\
";
  }

  static const char* value(const ::robotarminterface::singleServo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotarminterface::singleServo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.servoId);
      stream.next(m.position);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct singleServo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotarminterface::singleServo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotarminterface::singleServo_<ContainerAllocator>& v)
  {
    s << indent << "servoId: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.servoId);
    s << indent << "position: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.position);
    s << indent << "time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTARMINTERFACE_MESSAGE_SINGLESERVO_H
