// Generated by gencpp from file robotarminterface/stopSingleServo.msg
// DO NOT EDIT!


#ifndef ROBOTARMINTERFACE_MESSAGE_STOPSINGLESERVO_H
#define ROBOTARMINTERFACE_MESSAGE_STOPSINGLESERVO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotarminterface
{
template <class ContainerAllocator>
struct stopSingleServo_
{
  typedef stopSingleServo_<ContainerAllocator> Type;

  stopSingleServo_()
    : servoId(0)  {
    }
  stopSingleServo_(const ContainerAllocator& _alloc)
    : servoId(0)  {
  (void)_alloc;
    }



   typedef uint32_t _servoId_type;
  _servoId_type servoId;





  typedef boost::shared_ptr< ::robotarminterface::stopSingleServo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotarminterface::stopSingleServo_<ContainerAllocator> const> ConstPtr;

}; // struct stopSingleServo_

typedef ::robotarminterface::stopSingleServo_<std::allocator<void> > stopSingleServo;

typedef boost::shared_ptr< ::robotarminterface::stopSingleServo > stopSingleServoPtr;
typedef boost::shared_ptr< ::robotarminterface::stopSingleServo const> stopSingleServoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotarminterface::stopSingleServo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotarminterface::stopSingleServo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotarminterface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'robotarminterface': ['/home/owner/git/Kinematica/src/catkin_ws/src/kinematics/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotarminterface::stopSingleServo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotarminterface::stopSingleServo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotarminterface::stopSingleServo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotarminterface::stopSingleServo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotarminterface::stopSingleServo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotarminterface::stopSingleServo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotarminterface::stopSingleServo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c229a51eeb50adb8a4245c15dbd40200";
  }

  static const char* value(const ::robotarminterface::stopSingleServo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc229a51eeb50adb8ULL;
  static const uint64_t static_value2 = 0xa4245c15dbd40200ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotarminterface::stopSingleServo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotarminterface/stopSingleServo";
  }

  static const char* value(const ::robotarminterface::stopSingleServo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotarminterface::stopSingleServo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 servoId\n\
";
  }

  static const char* value(const ::robotarminterface::stopSingleServo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotarminterface::stopSingleServo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.servoId);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stopSingleServo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotarminterface::stopSingleServo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotarminterface::stopSingleServo_<ContainerAllocator>& v)
  {
    s << indent << "servoId: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.servoId);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTARMINTERFACE_MESSAGE_STOPSINGLESERVO_H
