// Generated by gencpp from file robotarminterface/stopServos.msg
// DO NOT EDIT!


#ifndef ROBOTARMINTERFACE_MESSAGE_STOPSERVOS_H
#define ROBOTARMINTERFACE_MESSAGE_STOPSERVOS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotarminterface
{
template <class ContainerAllocator>
struct stopServos_
{
  typedef stopServos_<ContainerAllocator> Type;

  stopServos_()
    : servoIds()  {
    }
  stopServos_(const ContainerAllocator& _alloc)
    : servoIds(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _servoIds_type;
  _servoIds_type servoIds;





  typedef boost::shared_ptr< ::robotarminterface::stopServos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotarminterface::stopServos_<ContainerAllocator> const> ConstPtr;

}; // struct stopServos_

typedef ::robotarminterface::stopServos_<std::allocator<void> > stopServos;

typedef boost::shared_ptr< ::robotarminterface::stopServos > stopServosPtr;
typedef boost::shared_ptr< ::robotarminterface::stopServos const> stopServosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotarminterface::stopServos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotarminterface::stopServos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotarminterface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'robotarminterface': ['/home/owner/git/Kinematica/src/catkin_ws/src/kinematics/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotarminterface::stopServos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotarminterface::stopServos_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotarminterface::stopServos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotarminterface::stopServos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotarminterface::stopServos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotarminterface::stopServos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotarminterface::stopServos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "58c2b1e06ba6865d4582bb6764fd753f";
  }

  static const char* value(const ::robotarminterface::stopServos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x58c2b1e06ba6865dULL;
  static const uint64_t static_value2 = 0x4582bb6764fd753fULL;
};

template<class ContainerAllocator>
struct DataType< ::robotarminterface::stopServos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotarminterface/stopServos";
  }

  static const char* value(const ::robotarminterface::stopServos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotarminterface::stopServos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32[] servoIds\n\
";
  }

  static const char* value(const ::robotarminterface::stopServos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotarminterface::stopServos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.servoIds);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stopServos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotarminterface::stopServos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotarminterface::stopServos_<ContainerAllocator>& v)
  {
    s << indent << "servoIds[]" << std::endl;
    for (size_t i = 0; i < v.servoIds.size(); ++i)
    {
      s << indent << "  servoIds[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.servoIds[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTARMINTERFACE_MESSAGE_STOPSERVOS_H
